# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-26 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ultima_postagem', models.DateTimeField(verbose_name='ultima_postagem')),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500)),
                ('curtidas', models.IntegerField(default=0)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Pessoa')),
            ],
        ),
    ]
